name = "coolvibes"
pages_build_output_dir = "./main"
type = "javascript"





kv_namespaces = [
    { binding = "wranglerKV", id = "574f7e0b3710496ebd90364a51f4f026" }
]

[vars]
variable1 = "somevalue"

[secrets]
mysecret = "not4u"

[secrets.foo]
bar = 'shhh'
